.DEFAULT_GOAL := help

images = taskTest:prod taskTest:latest taskTest:test-server taskTest:dev
containers = taskTest-dev taskTest-test-server

.PHONY: help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.PHONY: build
build: build-prod build-test-server build-dev  ## Build all Docker images, including for production, testing, and development

.PHONY: build-prod
build-prod:  ## Build Docker image for production
	docker build --target prod -t taskTest:prod -t taskTest:latest .

.PHONY: build-test-server
build-test-server:  ## Build Docker image for testing the server
	docker build -f Dockerfile.dev --target test-server -t taskTest:test-server .

.PHONY: build-dev
build-dev:  ## Build Docker image for development environment
	docker build -f Dockerfile.dev --target dev -t taskTest:dev .

.PHONY: test
test: test-server test-client  ## Run all tests, both server-side and client-side

.PHONY: test-server
test-server:  ## Run server tests
	@docker run --rm -it \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest"\
        --workdir="/opt/taskTest" \
        --env-file dev.env \
        taskTest:test-server \
        /bin/bash -c "pip install -e /opt/taskTest && python -m pytest /opt/taskTest/test"

.PHONY: test-client
test-client: clean-containers serve-test  ## Run client tests
	@docker run --rm -it \
        --mount type=bind,source="$(CURDIR)/taskTest/static",target="/e2e" \
        --net host \
        -w /e2e \
        cypress/included:6.6.0

.PHONY: serve
serve: clean-containers  ## Run development server
	@docker run --rm -d \
        --name taskTest-dev \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest" \
        --workdir="/opt/taskTest" \
        --env-file dev.env \
        -p 5000:5000 \
        taskTest:dev \
        /usr/local/bin/quart run --host 0.0.0.0

.PHONY: serve-test
serve-test: clean-containers  ## Run test server
	@docker run --rm -d \
        --name taskTest-test-server \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest" \
        --workdir="/opt/taskTest" \
        -e DATABASE_URL="sqlite://" \
        -p 5000:5000 \
        taskTest:dev \
        /usr/local/bin/quart run --host 0.0.0.0

.PHONY: shell
shell:  ## Run development environment shell
	@docker run --rm -it \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest" \
        --workdir="/opt/taskTest" \
        -w /opt/taskTest \
        --env-file dev.env \
        taskTest:dev \
        /bin/bash

.PHONY: db-migrations
db-migrations:  ## Generate database migrations
	@docker run --rm -it \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest" \
        --workdir="/opt/taskTest" \
        -w /opt/taskTest \
        --env-file dev.env \
        taskTest:dev \
        /usr/local/bin/alembic revision --autogenerate -m "autogenerated"

.PHONY: db-upgrade
db-upgrade:  ## Apply database migrations
	@docker run --rm -it \
        --mount type=bind,source="$(CURDIR)",target="/opt/taskTest" \
        --workdir="/opt/taskTest" \
        -w /opt/taskTest \
        --env-file dev.env \
        taskTest:dev \
        /usr/local/bin/alembic upgrade head

.PHONY: package
package:  ## Build Python source and wheel packages
	@python3 setup.py sdist bdist_wheel

.PHONY: clean
clean: clean-containers clean-images clean-files  ## Remove Docker containers & images and other files

.PHONY: clean-containers
clean-containers:  ## Remove Docker containers
	@docker stop $(containers) 2>/dev/null || true
	@docker container rm $(containers) 2>/dev/null || true

.PHONY: clean-images
clean-images:  ## Remove Docker images
	@docker image rm $(images) 2>/dev/null || true

.PHONY:
clean-files:  ## Remove __pycache__ and files produced by packaging
	@rm -rf __pycache__ test/__pycache__ taskTest/__pycache__
	@rm -rf *.egg-info build dist
